tasks:
  install:
    image: node:10-alpine
    command:
      - yarn
  test:
    image: node:10-alpine
    command:
      - yarn
    args:
      - test
  build:
    image: node:10-alpine
    command:
      - yarn
    args:
      - build
